FROM python:3.9
LABEL maintainer="tian.r.king@gmail.com"
LABEL version="v0.1"
# WORKDIR 

# 
# COPY ./requirements.txt /code/requirements.txt

# 
# RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./app /code/app

# 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
